"""add is_admin to users

Revision ID: 97eae9d900ad
Revises: 8a534c4a69f3
Create Date: 2026-03-29 18:11:59.683286
"""

# ruff: noqa: UP007, UP035, I001
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "97eae9d900ad"
down_revision: Union[str, None] = "8a534c4a69f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("is_admin", sa.Boolean(), server_default="false", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###
